### ISSUE TITLE
Malformed version number string ^1.13.12

### ISSUE THREAD

**Issue by zacstewart** [thoughtbot/ember-cli-rails#262]
Looks like using `Gem::Version` to match version numbers of Node packages isn't going to work very well. Node uses different version formats than ruby Gems, e.g. carets instead of `~>`

```
ArgumentError:
  Malformed version number string ^1.13.12
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli/helpers.rb:6:in `match_version?'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli/app.rb:205:in `check_ember_cli_version!'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli/app.rb:194:in `prepare'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli/app.rb:23:in `compile'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli/runner.rb:46:in `compile!'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli/runner.rb:17:in `process'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli-rails.rb:62:in `block in process_path'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli-rails.rb:86:in `block in each_app'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli-rails.rb:86:in `each'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli-rails.rb:86:in `each_app'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli-rails.rb:62:in `process_path'
# /home/rof/cache/bundler/ruby/2.2.0/gems/ember-cli-rails-0.4.0/lib/ember-cli/middleware.rb:13:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
# /home/rof/cache/bundler/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/web-console-2.2.1/lib/web_console/middleware.rb:39:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
# /home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
# /home/rof/cache/bundler/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
```

**Comment by seanpdoyle** [comment]
@zacstewart thanks for bringing this to our attention.

Unfortunately, you're right, our current approach isn't the best.

Could you elaborate on why you're using `^` instead of `~>`?

As a quick fix, would you be able to peg EmberCLI to a particular version, or change the `^` to `~>`?

**Comment by zacstewart** [comment]
Thanks for the quick response!

**Comment by seanpdoyle** [comment]
@zacstewart glad we could help resolve the issue!

Unfortunately, the fix will probably sit in `master` for a few more days.

The next release will be a minor version bump that will introduce some breaking changes (it's all for the best, I promise!).
