### ISSUE TITLE
sprockets error when using ember-cli with rails edge (5 alpha)

### ISSUE THREAD

**Issue by dchersey** [thoughtbot/ember-cli-rails#282]
I've been chasing a weird issue, and have isolated it down as follows:

I am running Rails edge and am kicking the tires of action cable using a simple chat app. I want  this to work with ember-cli.  In order to cleanly use action cable, the coffeescript needs to be included using the rails asset pipeline because of some internal linkages provided by the root cable.coffee.erb script.

I am doing this using a custom controller chat_controller:
```ruby
   class ChatController < ::ApplicationController

    def index
      render layout: false
    end

  end
```

with index.html.erb:
```erb
<%= render_ember_app :ui do |head| %>
  <% head.append do %>

    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
  <% end %>
<% end %>
```

Everything works fine with the rails asset pipeline provided I hit a rails view first (for example /messages defined in the below routes.rb)
```ruby
  resources :messages, only: [:index, :create]
  resources :sessions, only: [:new, :create]

  mount_ember_app :ui, to: "/" , controller: 'chat', action: 'index'
```

But when I restart my server (puma) and hit the root / first, I get the following, and also get it for every rails view that I hit directly (i.e. /messages as above).

```
ctionView::Template::Error (undefined method `start_with?' for /\Aui\//:Regexp):
    3: 
    4:     <%= csrf_meta_tags %>
    5: 
    6:     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    7:     
    8:   <% end %>
    9: <% end %>
  app/views/chat/index.html.erb:6:in `block (2 levels) in _app_views_chat_index_html_erb___588958813259362485_70275343079360'
  app/views/chat/index.html.erb:2:in `block in _app_views_chat_index_html_erb___588958813259362485_70275343079360'
  app/views/chat/index.html.erb:1:in `_app_views_chat_index_html_erb___588958813259362485_70275343079360'
  app/controllers/chat_controller.rb:4:in `index'


  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.9ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/actionpack/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.1ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/actionpack/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (42.8ms)
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from block in render_exception_with_web_console at /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/extensions.rb:14)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/templates/_markup.html.erb (0.3ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.1ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/templates/console.js.erb within layouts/javascript (39.1ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/web-console-e7dcc5f7a773/lib/web_console/templates/index.html.erb (83.1ms)
```
My bundle list shows: 
```
Gems included by the bundle:
  * actioncable (0.0.3 6be2604)
  * actionmailer (5.0.0.alpha 0ebb0f6)
  * actionpack (5.0.0.alpha 0ebb0f6)
  * actionview (5.0.0.alpha 0ebb0f6)
  * activejob (5.0.0.alpha 0ebb0f6)
  * activemodel (5.0.0.alpha 0ebb0f6)
  * activerecord (5.0.0.alpha 0ebb0f6)
  * activesupport (5.0.0.alpha 0ebb0f6)
  * arel (7.0.0.alpha 3c429c5)
  * builder (3.2.2)
  * bundler (1.10.6)
  * byebug (8.2.0)
  * celluloid (0.16.0)
  * coffee-rails (4.1.0 c05fb72)
  * coffee-script (2.4.1)
  * coffee-script-source (1.10.0)
  * concurrent-ruby (1.0.0)
  * debug_inspector (0.0.2)
  * em-hiredis (0.3.0)
  * ember-cli-rails (0.5.1)
  * erubis (2.7.0)
  * eventmachine (1.0.8)
  * execjs (2.6.0)
  * faye-websocket (0.10.1)
  * globalid (0.3.6)
  * hiredis (0.5.2)
  * hitimes (1.2.3)
  * i18n (0.7.0)
  * jbuilder (2.3.2)
  * jquery-rails (4.0.5)
  * json (1.8.3)
  * loofah (2.0.3)
  * mail (2.6.3)
  * method_source (0.8.2)
  * mime-types (2.6.2)
  * mini_portile (0.6.2)
  * minitest (5.8.2)
  * multi_json (1.11.2)
  * nokogiri (1.6.6.2)
  * non-stupid-digest-assets (1.0.5)
  * puma (2.15.3)
  * rack (2.0.0.alpha c393176)
  * rack-test (0.6.3)
  * rails (5.0.0.alpha 0ebb0f6)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-html-sanitizer (1.0.2)
  * railties (5.0.0.alpha 0ebb0f6)
  * rake (10.4.2)
  * redis (3.2.2)
  * sass (3.4.19)
  * sass-rails (6.0.0 6e4eee7)
  * spring (1.4.1)
  * sprockets (4.0.0 9bb491e)
  * sprockets-rails (3.0.0.beta3 06d84e9)
  * sqlite3 (1.3.11)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * timers (4.0.4)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * uglifier (2.7.2)
  * web-console (3.0.0 e7dcc5f)
  * websocket-driver (0.6.3)
  * websocket-extensions (0.1.2)
```

You can see/reproduce this issue by cloning https://github.com/dchersey/ember-cli-chat.git

After doing bundle install, start rails and hit localhost:3000.  Error happens.
Restart the server and hit localhost:3000/messages -- no error
then hit localhost:3000 -- no error

**Comment by seanpdoyle** [comment]
Thanks for opening this issue and bringing this to our attention!

It looks like you're pushing the boundaries of whats possible.

Unfortunately, I'm not too confident in action cable and EmberCLI interacting in a predictable way, since they're two wildly different flows happening in Rails-land and Ember-land respectively.

Having said that, you shouldn't be getting a NoMethodError.

It looks like it blows up when the `ember-cli-rails`-generated regex (assuming your EmberCLI app is configured to be named `ui`).

[This code](https://github.com/thoughtbot/ember-cli-rails/blob/1adb46487c21e5ac702349ec0630ca6d8f5203ba/lib/ember-cli/sprockets.rb#L10-L15) is responsible for registering that Regexp with Sprockets.

We're not calling `start_with?` in `ember-cli-rails` (as you can see [here](https://github.com/thoughtbot/ember-cli-rails/search?utf8=%E2%9C%93&q=start_with)).

It's possible that the newest version of the Asset Pipeline no longer supports regular expressions in their precompile list.

Like I said, you're on the bleeding edge here, so I'm not sure how I can help.

**Comment by dchersey** [comment]
Thanks for the quick response!  
I removed the action-cable dependency and was able to isolate the problem further to any embedding of sprockets references inside the render_ember_app block (and yes, my app is called :ui in initializers/ember.rb)

```erb
<%= render_ember_app :ui do |head| %>
  <% head.append do %>

    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <% end %>
<% end %>
```

The application.js no longer references anything that is not part of rails:

```javascript
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .
```

I agree it's likely that the asset pipeline no longer supports wildcards the same way, but why would it work when you hit a rails view first (/messages) url, work when you then hit the ember-cli view at /,
but fail when you hit the ember-cli path first?

Something in render_ember_app seems to be breaking the asset pipeline. Is there a difference in the order that things are loaded/required?  Maybe I will try it with eager_loading.

David

**Comment by dchersey** [comment]
Well, tried config.eager_load = true in my development.rb and got another clue when starting the server:

```
Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:411:in `const_defined?': wrong constant name Ember-cli (NameError)
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:411:in `qualified_const_defined?'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:173:in `block in watch_namespaces'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:171:in `map'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:171:in `watch_namespaces'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:678:in `new_constants_in'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:491:in `load_file'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:388:in `block in require_or_load'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/concurrency/share_lock.rb:115:in `exclusive'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:369:in `require_or_load'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:345:in `depend_on'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/activesupport/lib/active_support/dependencies.rb:261:in `require_dependency'
	from /Users/david/.rvm/gems/ruby-2.2.2/bundler/gems/rails-0ebb0f61c3c6/railties/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
```

Any thoughts?

**Comment by seanpdoyle** [comment]
@dchersey very interesting.

I had a hunch that I'd need to underscore the `ember-cli` directory.

Checkout https://github.com/thoughtbot/ember-cli-rails/pull/283 and try out the `sd-underscore` branch.

**Comment by dchersey** [comment]
You were right -- that resolved the `eager_load: true` issue!

However eager-loading did not resolve the original problem; it still fails rendering the ember template unless I hit a rails view first :(

I updated my example on github to reflect what I've changed.
