### ISSUE TITLE
assets:precompile fails for production on heroku

### ISSUE THREAD

**Issue by arinhouck** [thoughtbot/ember-cli-rails#305]
Recently updated to latest version of ember-cli-rails and tried to push to heroku. `bundle exec rake assets:precompile RAILS_ENV=production` works locally but not on heroku.

```
TypeError: no implicit conversion of nil into String
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/path_set.rb:93:in `initialize'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/path_set.rb:93:in `Pathname'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/path_set.rb:93:in `block (2 levels) in <class:PathSet>'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/path_set.rb:92:in `tap'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/path_set.rb:92:in `block in <class:PathSet>'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/path_set.rb:9:in `instance_exec'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/path_set.rb:9:in `block in define_path'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/shell.rb:40:in `install'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember_cli/app.rb:52:in `install_dependencies'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember-cli-rails.rb:76:in `block in each_app'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember-cli-rails.rb:76:in `each'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember-cli-rails.rb:76:in `each_app'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/ember-cli-rails.rb:42:in `install_dependencies!'
remote:        /tmp/build_90c9fe3f9859b1a6fd787aff2d366894/vendor/bundle/ruby/2.2.0/gems/ember-cli-rails-0.5.5/lib/tasks/ember-cli.rake:14:in `block (2 levels) in <top (required)>'
```

**Comment by seanpdoyle** [comment]
@arinhouck thanks for opening this issue and bringing this to our attention.

The [lines linked to in that stack trace](https://github.com/thoughtbot/ember-cli-rails/blob/v0.5.5/lib/ember_cli/path_set.rb#L92-L93) correspond to this method:

```rb
    define_path :bower do
      app_options.fetch(:bower_path) { configuration.bower_path }.tap do |path|
        unless Pathname(path).executable?
          fail DependencyError.new <<-MSG.strip_heredoc
          Bower is required by EmberCLI
          Install it with:
              $ npm install -g bower
          MSG
        end
      end
    end
```

The failure message gives me a hunch that you don't have a `bower` executable installed on Heroku.

Have you run `rails g ember-cli:heroku` generator? Checkout the [Heroku](https://github.com/thoughtbot/ember-cli-rails#heroku) section of the README for details.

Closing this issue for now. If my assumption is way off and you've properly setup your project for Heroku, say so and I'll reopen.

**Comment by arinhouck** [comment]
I have previously had heroku working with an older version of ember-cli-rails. I ran that command, and it fails on precompile assets but doesn't really tell me much. I had already updated build packs because I was using some other method that was previously shown.



Here is what I noticed during build
```
remote:        > undefined postinstall /tmp/build_8be93a93767463c0e1e177ec5ba17595
remote:        > ./bin/heroku_install
```

```
remote:        Bundle complete! 28 Gemfile dependencies, 84 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (34.71s)
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        npm WARN prefer global jshint@2.6.3 should be installed with -g
remote:        npm WARN prefer global npm@2.14.10 should be installed with -g
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
```

package.json in rails
```
{
  "scripts": {
    "postinstall": "./bin/heroku_install"
  },
  "devDependencies": {
    "bower": "*"
  },
  "cacheDirectories": [
    "frontend/node_modules",
    "frontend/bower_components",
    "node_modules"
  ]
}
```
Then my other package.json hasn't changed that is inside my frontend (ember app folder).

**Comment by seanpdoyle** [comment]
Have you modified your Heroku environment?

```bash
$ heroku buildpacks:clear
$ heroku buildpacks:add --index 1 https://github.com/heroku/heroku-buildpack-nodejs
$ heroku buildpacks:add --index 2 https://github.com/heroku/heroku-buildpack-ruby
$ heroku config:set NPM_CONFIG_PRODUCTION=false
$ heroku config:unset SKIP_EMBER
```

Does `bin/heroku_install` exist in your project?

**Comment by seanpdoyle** [comment]
Have you also ensured that the `.buildpacks` file no longer exists?

**Comment by arinhouck** [comment]
Cleared build packs again to make sure and configured. Yes to `bin/heroku_install`. I removed my .buildpacks file from repo. Still have this message:
```
remote:        > undefined postinstall /tmp/build_ea479d4174dce245466e6f65b41e21de
remote:        > ./bin/heroku_install
```

**Comment by seanpdoyle** [comment]
That's very confusing.

Are you sure that 

```bash
$ heroku config:set NPM_CONFIG_PRODUCTION=false
``` 

has been run and configured? It sounds like `bower` isn't recognized.

**Comment by seanpdoyle** [comment]
I was able to update to the latest (`0.5.6`) and deploy to Heroku:

```
2.2.3 in ember-cli-rails-heroku-example/ on sd-latest
› g push heroku sd-latest:master -f
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 478 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching set buildpack https://github.com/heroku/heroku-buildpack-nodejs... done
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version (latest stable) via semver.io...
remote:        Downloading and installing node 5.0.0...
remote:        Using default npm version: 3.3.6
remote:
remote: -----> Restoring cache
remote:        Loading 3 from cacheDirectories (package.json):
remote:        - frontend/node_modules
remote:        - frontend/bower_components
remote:        - node_modules
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote:        > undefined postinstall /tmp/build_32708e7b0b95ed950bc883a79f7c263a
remote:        > ./bin/heroku_install
remote:
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 3 cacheDirectories (package.json):
remote:        - frontend/node_modules
remote:        - frontend/bower_components
remote:        - node_modules
remote:
remote: -----> Build succeeded!
remote:        └── bower@1.6.5
remote:
remote: -----> Fetching set buildpack https://github.com/heroku/heroku-buildpack-ruby... done
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.2.3
remote: -----> Installing dependencies using bundler 1.9.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Fetching gem metadata from https://rubygems.org/...........
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Using i18n 0.7.0
remote:        Using rake 10.4.2
remote:        Installing thread_safe 0.3.4
remote:        Using builder 3.2.2
remote:        Using erubis 2.7.0
remote:        Using mini_portile 0.6.2
remote:        Installing minitest 5.5.1
remote:        Using mime-types 2.4.3
remote:        Using arel 6.0.0
remote:        Using coffee-script-source 1.8.0
remote:        Using execjs 2.2.2
remote:        Using thor 0.19.1
remote:        Using non-stupid-digest-assets 1.0.5
remote:        Installing hike 1.2.3
remote:        Installing rack 1.6.0
remote:        Using tilt 1.4.1
remote:        Using pg 0.18.1
remote:        Using bundler 1.9.7
remote:        Using rails_serve_static_assets 0.0.3
remote:        Using rails_stdout_logging 0.0.3
remote:        Using rdoc 4.2.0
remote:        Using sass 3.4.9
remote:        Using tzinfo 1.2.2
remote:        Installing multi_json 1.10.1
remote:        Using mail 2.6.3
remote:        Using coffee-script 2.3.0
remote:        Using rack-test 0.6.3
remote:        Using rails_12factor 0.0.3
remote:        Installing sprockets 2.12.3
remote:        Installing nokogiri 1.6.5
remote:        Installing json 1.8.2
remote:        Using activesupport 4.2.0
remote:        Using sdoc 0.4.1
remote:        Using uglifier 2.7.0
remote:        Using rails-deprecated_sanitizer 1.0.3
remote:        Using globalid 0.3.0
remote:        Using activemodel 4.2.0
remote:        Using climate_control 0.0.3
remote:        Using jbuilder 2.2.6
remote:        Using activejob 4.2.0
remote:        Using activerecord 4.2.0
remote:        Using cocaine 0.5.8
remote:        Installing rails-dom-testing 1.0.5
remote:        Installing loofah 2.0.1
remote:        Installing rails-html-sanitizer 1.0.1
remote:        Using actionview 4.2.0
remote:        Using actionpack 4.2.0
remote:        Using actionmailer 4.2.0
remote:        Using railties 4.2.0
remote:        Using sprockets-rails 2.2.2
remote:        Using coffee-rails 4.1.0
remote:        Using ember-cli-rails 0.5.6
remote:        Using jquery-rails 4.0.3
remote:        Using rails 4.2.0
remote:        Using sass-rails 5.0.1
remote:        Using turbolinks 2.5.3
remote:        Bundle complete! 14 Gemfile dependencies, 56 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (11.82s)
remote:        Cleaning up the bundler cache.
remote:        Removing thread_safe (0.3.5)
remote:        Removing multi_json (1.11.2)
remote:        Removing rails-html-sanitizer (1.0.2)
remote:        Removing json (1.8.3)
remote:        Removing loofah (2.0.3)
remote:        Removing rack (1.6.4)
remote:        Removing rails-dom-testing (1.0.7)
remote:        Removing nokogiri (1.6.6.4)
remote:        Removing minitest (5.8.3)
remote:        Removing sprockets (3.4.0)
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        npm WARN prefer global jshint@2.8.0 should be installed with -g
remote:        npm WARN prefer global npm@2.14.10 should be installed with -g
remote:        Asset precompilation completed (28.58s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
remote:
remote:
remote: -----> Discovering process types
remote:        Procfile declares types     -> web
remote:        Default types for buildpack -> console, rake, worker
remote:
remote: -----> Compressing... done, 80.6MB
remote: -----> Launching... done, v76
remote:        https://ember-cli-rails-heroku-example.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To git@heroku.com:ember-cli-rails-heroku-example.git
 + 4cb6723...d157943 sd-latest -> master (forced update)
```

Note, that output contains

```
remote:        > undefined postinstall /tmp/build_32708e7b0b95ed950bc883a79f7c263a
remote:        > ./bin/heroku_install
```

so that might be a red herring

**Comment by arinhouck** [comment]
My build is succeeding for bower on node.
```
e:        ├── user-home@1.1.1
remote:        └─┬ which@1.2.0
remote:        └─┬ is-absolute@0.1.7
remote:        └── is-relative@0.1.3
remote:        
remote: 
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 3 cacheDirectories (package.json):
remote:        - frontend/node_modules
remote:        - frontend/bower_components
remote:        - node_modules
remote: 
remote: -----> Build succeeded!
remote:        └── bower@1.4.2
```

What drives me insane is the failure on assets now has no message. Is there a way to get something more verbose?
```
remote:        Bundle complete! 28 Gemfile dependencies, 84 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (39.33s)
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        npm WARN prefer global jshint@2.6.3 should be installed with -g
remote:        npm WARN prefer global npm@2.14.10 should be installed with -g
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
```

**Comment by seanpdoyle** [comment]
@arinhouck you could try setting `EMBER_CLI_RAILS_VERBOSE=true`. It sounds like you're running Heroku in `production`, so it should be verbose anyway:

https://github.com/thoughtbot/ember-cli-rails/blob/903e7b3ca1caca1fb352127852d5d944f6660b40/lib/ember_cli/shell.rb#L81-L87

Another option would be to clear your cache. It might not be effective, since it sounds like you haven't yet successfully deployed, but

```
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 3 cacheDirectories (package.json):
remote:        - frontend/node_modules
remote:        - frontend/bower_components
remote:        - node_modules
```

makes it seem like you're saving a cache.

To clear your deploy cache, set your root level `package.json`'s `"cacheDirectories": []`.

Also, are you serving *any* rails side assets, or is this all EmberCLI?

**Comment by arinhouck** [comment]
I am serving Rails assets as well. I have tried with `:uglifier` alongside `minifyJs: false` and as nil with `minifyJs: true`. I think it may be a Rails problem now.

Still no message:
```
remote:        Cleaning up the bundler cache.
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        npm WARN prefer global jshint@2.6.3 should be installed with -g
remote:        npm WARN prefer global npm@2.14.10 should be installed with -g
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
```

**Comment by arinhouck** [comment]
Here are my current configs in production.rb:
```
  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true
  config.serve_static_files = true
  # Compress JavaScripts and CSS.
  config.assets.js_compressor = nil

**Comment by arinhouck** [comment]
So I finally got it to build now. However now I get a 404 error on production for frontend.css and nothing on the page loads.

**Comment by seanpdoyle** [comment]
@arinhouck that's great news!

What style of EmberCLI-Rails integration are you using? 

`render_ember_app` or `include_ember_*_tags`?

**Comment by arinhouck** [comment]
```
<%= include_ember_script_tags :frontend %>
<%= include_ember_stylesheet_tags :frontend %>
```

You can see the error on production @ gradebuildr.com

**Comment by seanpdoyle** [comment]
@arinhouck thanks for providing your Application layout.

To start, I would recommend only using one or the other styles of embedding the Ember application.

If you can help it, you should prefer to call `render_ember_app`, injecting the necessary Rails-generated markup, since it is the preferred approach for future versions.

If you can't use `render_ember_app`, you should remove the call to `render_ember_app`.

**Comment by seanpdoyle** [comment]
Additionally, since your project is now compiling
