### ISSUE TITLE
Passed.png asset not generated on bootstrap

### ISSUE THREAD

**Issue by cometman** [thoughtbot/ember-cli-rails#358]
Creating new app from the installation guide produces a missing `passed.png` asset.  This asset should be found after generating the application within `/frontend/bower_components/ember-qunit-notifications/passed.png`

Downloading the asset manually from https://github.com/dockyard/ember-qunit-notifications/blob/master/passed.png as a quick fix.

Ruby 2.1.1 Rails 4.2.5

**Comment by seanpdoyle** [comment]
@cometman thanks for opening this issue.

I'm not sure I understand how this error came about, This sounds like am EmberCLI issue.

> Creating new app from the installation guide produces a missing passed.png asset.

In what way? Are you running `ember new`? What is complaining about the missing asset?

**Comment by cometman** [comment]
You are right, looks like an issue with EmberCLI.

Yes, this happens when creating a new app with `ember new`.  

`Error: ENOENT, no such file or directory 'front-end/tmp/funnel-input_base_path-dpVf9ewX.tmp/0/bower_components/ember-qunit-notifications/passed.png'
    at Error (native)
    at Object.fs.lstatSync (fs.js:796:18)
    at symlink (/Users/Clay/Developer/ember-api-front-end/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26)
    at Function.symlinkOrCopySync (front-end/node_modules/ember-cli/node_modules/symlink-or-copy/index.js:58:5)
    at Funnel._copy (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:398:19)
    at Funnel.processFile (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:381:8)
    at Funnel.applyPatch [as _applyPatch] (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:298:12)
    at Funnel.<anonymous> (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:250:10)
    at Array.forEach (native)
    at Funnel.processFilters (front-end/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:249:9)`

**Comment by seanpdoyle** [comment]
Closing in favor of https://github.com/ember-cli/ember-cli/issues/5226

Thanks!
