### ISSUE TITLE
"no implicit conversion of nil into String" during assets precompilation

### ISSUE THREAD

**Issue by osxi** [thoughtbot/ember-cli-rails#383]
I'm using version 0.7.0 of both the gem and Ember addon.

This doesn't happen to me in development, but on CI, I get the following error when running `rake assets:precompile`:
```
rake aborted!
no implicit conversion of nil into String
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember_cli/path_set.rb:68:in `initialize'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember_cli/path_set.rb:68:in `Pathname'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember_cli/path_set.rb:68:in `block in bower'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember_cli/path_set.rb:67:in `tap'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember_cli/path_set.rb:67:in `bower'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember_cli/shell.rb:41:in `install'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember_cli/app.rb:68:in `install_dependencies'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember-cli-rails.rb:65:in `block in each_app'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember-cli-rails.rb:65:in `each'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember-cli-rails.rb:65:in `each_app'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/ember-cli-rails.rb:36:in `install_dependencies!'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/ember-cli-rails-0.7.0/lib/tasks/ember-cli.rake:14:in `block (2 levels) in <top (required)>'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/mnt/home/abc123/bundle/ruby/2.2.0/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => assets:precompile => ember:compile => ember:install
(See full trace by running task with --trace)
command exited with status 1
```

config/initializers/ember.rb:
```
EmberCli.configure do |c|
  c.app :frontend
end
```

What's interesting is that the output from the previous command on CI is bower install, which succeeds. Seems something is nil when it should be a path to `bower`?

**Comment by osxi** [comment]
As per https://github.com/thoughtbot/ember-cli-rails/issues/319, I altered my config/initializers/ember.rb to look like:
```
EmberCli.configure do |c|
  c.app :frontend, bower_path: Rails.root.join('frontend', 'node_modules', 'bower', 'bin', 'bower')
end
```

That gets things working.

Is this actually a bug?

**Comment by seanpdoyle** [comment]
@osxi thanks for opening this issue!

When you're executing `npm install bower`, are you installing globally with the `-g` flag?

**Comment by osxi** [comment]
@seanpdoyle, you're welcome!

The underlying issue turned out being related to bower not being in the $PATH.

**Comment by seanpdoyle** [comment]
:clap: thanks for posting back here with your resolution!
